version: '3.3'
services:
  db2:
    container_name: db2
    privileged: true
    ports:
      - '50000:50000'
    environment:
      - LICENSE=accept
      - DB2INST1_PASSWORD=<your-password>
      - DBNAME=testdb
    volumes:
      - 'db2-data:/database'
    image: ibmcom/db2:11.5.0.0

volumes:
  db2-data:
